### PR TITLE
Picture helper - progressive lazyloading

### PR DESCRIPTION
**Pull request by ErikHen**
Possible to have progressive lazy loading of images.
Updated the documentation for Picture helper.

### CODE REVIEW

**Comment by ErikHen** [comment]
Forgot to mention that this change is a breaking change for the Picture helper (if lazy loading have been used).

**Comment by vnbaaij** [comment]
So in a strict SemVer world, we would need to give this a new major version number. What do you think?

**Comment by ErikHen** [comment]
It feels a bit silly for this very minor thing, but I would say yes :-). If using semver, use it properly.

**Comment by vnbaaij** [comment]
Version 4.0.0 submitted to the NuGet feed

**Pull request merged**
